### ISSUE TITLE
Fix FieldGetter implementation for Option<T>

### ISSUE THREAD

**Issue by Babidiii** [kunai-project/gene-rs#1]
# Bug report

## Description

The implementation of FieldGetter for an Option<T>  
- always returns an error `FieldNotFound` for an iterator with `len > 0` 
- cause a stack overflow for an iterator with `len == 0` (due to the recursive call)

```rust
// gene/src/event.rs
fn get_from_iter(&self, i: core::slice::Iter<'_, std::string::String>) -> Option<FieldValue> {
        if i.len() > 0 {
            return None;
         }
        self.get_from_iter(i) // << recursive call
     }
 }
```
## Minimalist example

```toml
# ...
[dependencies]
gene = { git = "https://github.com/0xrawsec/gene-rs", branch = "main" }
event_derive = { git = "https://github.com/0xrawsec/gene-rs", branch = "main" }
serde_yaml = { version = "0.9" }
serde = { version = "1.0", features = ["derive"] }
```

```rust
use event_derive::{Event, FieldGetter};
use gene::{Engine, Event, FieldGetter, FieldValue, Rule};
use serde::{Deserialize, Serialize};

#[derive(FieldGetter, Serialize, Deserialize, Debug)]
pub struct SomeStruct {
    some_value: u64,
}

#[derive(Event, FieldGetter, Serialize, Deserialize, Debug)]
#[event(id = 1, source = "whatever".into())]
pub struct SomeEvent {
    pub type_id: String,
    pub data: Option<SomeStruct>,
}

fn main() {
    let rule = r#"
---
name: test
matches:
    $a: .type_id ~= 'id'
    $b: .data.some_value &= '1'
condition: $a and $b 
..."#;

    let d: Rule = serde_yaml::from_str(rule).expect("deserialization");

    let mut engine = Engine::new();
    engine.insert_rule(d).expect("insert rule");

    let event = SomeEvent {
        type_id: "some_id".to_string(),
        data: Some(SomeStruct { some_value: 1 }),
    };

    let r = engine.scan(&event).expect("scan");

    dbg!(r);
}
```
```
[src/main.rs:37:5] &event = SomeEvent {
    type_id: "some_id",
    data: Some(
        SomeStruct {
            some_value: 1,
        },
    ),
}
[src/main.rs:38:5] engine.scan(&event) = Err(
    (
        None,
        Rule(
            Wrap(
                "test",
                Condition(
                    MatchError(
                        FieldNotFound(
                            ".data.some_value",
                        ),
                    ),
                ),
            ),
        ),
    ),
)
```

If the rule `$b` is changed for `$b: .data &= '1'` then a stack overflow is triggered.

## Fix

Here is a minimalist fix
```diff
diff --git a/gene/src/event.rs b/gene/src/event.rs
index 85955ae..10818db 100644
--- a/gene/src/event.rs
+++ b/gene/src/event.rs
@@ -87,10 +87,11 @@ where
 {
     #[inline]
     fn get_from_iter(&self, i: core::slice::Iter<'_, std::string::String>) -> Option<FieldValue> {
-        if i.len() > 0 {
-            return None;
+        if let Some(v) = self {
+            v.get_from_iter(i)
+        } else {
+            None
         }
-        self.get_from_iter(i)
     }
 }
```
The implementation should take care of the len in order to retrieve 
- The `Option` in its whole when `len == 0`
  + FieldValue should be updated in order to handle Option (None is not suitable)
- A value from the inner value of the variant `Some` when `len > 0`

The fix could be tested with
```toml
gene = { git = "https://github.com/Babidiii/gene-rs", branch = "main" }
event_derive = { git = "https://github.com/Babidiii/gene-rs", branch = "main" }
```
