### ISSUE TITLE
match with same names

### ISSUE THREAD

**Issue by qjerome** [kunai-project/gene-rs#9]
Two matches with the same name like the following do not raise any error and makes the condition confusing. Maybe this is due to a quirk in serde_yaml crate.

```yaml
name: test
matches:
    $ip: .ip == "8.8.4.4"
    $ip: .ip ~= "^8\.8\."
condition: none of $ip
```
